//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 12:10:28 PM CEST 
//


package com.tas.model.threats;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elementsList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="element" type="{https://www.tas.org/tas-schemas}elementType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="assetsList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="asset" type="{https://www.tas.org/tas-schemas}assetType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="threatsList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="threat" type="{https://www.tas.org/tas-schemas}threatType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="threatDefinitions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="threatsForElement" type="{https://www.tas.org/tas-schemas}threatsForElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elementsList",
    "assetsList",
    "threatsList",
    "threatDefinitions"
})
@XmlRootElement(name = "definitions")
public class Definitions {

    @XmlElement(required = true)
    protected Definitions.ElementsList elementsList;
    @XmlElement(required = true)
    protected Definitions.AssetsList assetsList;
    @XmlElement(required = true)
    protected Definitions.ThreatsList threatsList;
    @XmlElement(required = true)
    protected Definitions.ThreatDefinitions threatDefinitions;

    /**
     * Gets the value of the elementsList property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.ElementsList }
     *     
     */
    public Definitions.ElementsList getElementsList() {
        return elementsList;
    }

    /**
     * Sets the value of the elementsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.ElementsList }
     *     
     */
    public void setElementsList(Definitions.ElementsList value) {
        this.elementsList = value;
    }

    /**
     * Gets the value of the assetsList property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.AssetsList }
     *     
     */
    public Definitions.AssetsList getAssetsList() {
        return assetsList;
    }

    /**
     * Sets the value of the assetsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.AssetsList }
     *     
     */
    public void setAssetsList(Definitions.AssetsList value) {
        this.assetsList = value;
    }

    /**
     * Gets the value of the threatsList property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.ThreatsList }
     *     
     */
    public Definitions.ThreatsList getThreatsList() {
        return threatsList;
    }

    /**
     * Sets the value of the threatsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.ThreatsList }
     *     
     */
    public void setThreatsList(Definitions.ThreatsList value) {
        this.threatsList = value;
    }

    /**
     * Gets the value of the threatDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.ThreatDefinitions }
     *     
     */
    public Definitions.ThreatDefinitions getThreatDefinitions() {
        return threatDefinitions;
    }

    /**
     * Sets the value of the threatDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.ThreatDefinitions }
     *     
     */
    public void setThreatDefinitions(Definitions.ThreatDefinitions value) {
        this.threatDefinitions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="asset" type="{https://www.tas.org/tas-schemas}assetType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asset"
    })
    public static class AssetsList {

        @XmlElement(required = true)
        protected List<AssetType> asset;

        /**
         * Gets the value of the asset property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the asset property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAsset().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AssetType }
         * 
         * 
         */
        public List<AssetType> getAsset() {
            if (asset == null) {
                asset = new ArrayList<AssetType>();
            }
            return this.asset;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="element" type="{https://www.tas.org/tas-schemas}elementType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "element"
    })
    public static class ElementsList {

        @XmlElement(required = true)
        protected List<ElementType> element;

        /**
         * Gets the value of the element property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the element property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElementType }
         * 
         * 
         */
        public List<ElementType> getElement() {
            if (element == null) {
                element = new ArrayList<ElementType>();
            }
            return this.element;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="threatsForElement" type="{https://www.tas.org/tas-schemas}threatsForElementType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "threatsForElement"
    })
    public static class ThreatDefinitions {

        protected List<ThreatsForElementType> threatsForElement;

        /**
         * Gets the value of the threatsForElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the threatsForElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getThreatsForElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ThreatsForElementType }
         * 
         * 
         */
        public List<ThreatsForElementType> getThreatsForElement() {
            if (threatsForElement == null) {
                threatsForElement = new ArrayList<ThreatsForElementType>();
            }
            return this.threatsForElement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="threat" type="{https://www.tas.org/tas-schemas}threatType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "threat"
    })
    public static class ThreatsList {

        @XmlElement(required = true)
        protected List<ThreatType> threat;

        /**
         * Gets the value of the threat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the threat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getThreat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ThreatType }
         * 
         * 
         */
        public List<ThreatType> getThreat() {
            if (threat == null) {
                threat = new ArrayList<ThreatType>();
            }
            return this.threat;
        }

    }

}
