//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 12:10:28 PM CEST 
//


package com.tas.model.threats;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tas.model.threats package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tas.model.threats
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link ThreatsForCIA }
     * 
     */
    public ThreatsForCIA createThreatsForCIA() {
        return new ThreatsForCIA();
    }

    /**
     * Create an instance of {@link Definitions.ElementsList }
     * 
     */
    public Definitions.ElementsList createDefinitionsElementsList() {
        return new Definitions.ElementsList();
    }

    /**
     * Create an instance of {@link Definitions.AssetsList }
     * 
     */
    public Definitions.AssetsList createDefinitionsAssetsList() {
        return new Definitions.AssetsList();
    }

    /**
     * Create an instance of {@link Definitions.ThreatsList }
     * 
     */
    public Definitions.ThreatsList createDefinitionsThreatsList() {
        return new Definitions.ThreatsList();
    }

    /**
     * Create an instance of {@link Definitions.ThreatDefinitions }
     * 
     */
    public Definitions.ThreatDefinitions createDefinitionsThreatDefinitions() {
        return new Definitions.ThreatDefinitions();
    }

    /**
     * Create an instance of {@link ThreatsForElementType }
     * 
     */
    public ThreatsForElementType createThreatsForElementType() {
        return new ThreatsForElementType();
    }

    /**
     * Create an instance of {@link ThreatType }
     * 
     */
    public ThreatType createThreatType() {
        return new ThreatType();
    }

    /**
     * Create an instance of {@link ThreatDefinitionType }
     * 
     */
    public ThreatDefinitionType createThreatDefinitionType() {
        return new ThreatDefinitionType();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link AssetType }
     * 
     */
    public AssetType createAssetType() {
        return new AssetType();
    }

    /**
     * Create an instance of {@link ThreatsForCIA.Threat }
     * 
     */
    public ThreatsForCIA.Threat createThreatsForCIAThreat() {
        return new ThreatsForCIA.Threat();
    }

}
