//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.DiagramPattern;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "Asset:_Admin_password"
    when
     	DiagramPattern($list : coreDestination.getAssets().getAsset())  
     	//DiagramPattern($list : coreFlow.getValue().getAssets().getAsset())  
     	$value : Assets.Asset() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.ADMINISTRATOR_PASSWORD         
    then
        drools.setFocus("ap_check_destination");
end


rule "AP:_Check_process"
	agenda-group "ap_check_destination"
    when
        component: DiagramPattern(coreDestination instanceof Process)                    
    then
        drools.setFocus("ap_process");
end


rule "AP:_Check_external"
	agenda-group "ap_check_destination"
    when
        component: DiagramPattern(coreDestination instanceof ExternalEntity)                    
    then
        drools.setFocus("ap_external");
end


rule "AP:_Check_datastore"
	agenda-group "ap_check_destination"
    when
        component: DiagramPattern(coreDestination instanceof DataStore)                    
    then
        drools.setFocus("ap_datastore");
end


rule "AP_Process:_Resource"
	agenda-group "ap_process"
    when
        component: DiagramPattern(coreSource instanceof ExternalEntity)                    
    then
        component.addVulnerability(VulnerabilityCode.INJECTION_SQL);
end

