//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.*;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "Asset:_Session_Cookie"
    when
     	DiagramPattern($list : assets)  
     	$value : Assets.Asset() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.SESSION_COOKIE               
    then
        drools.setFocus("sc_check_destination");
end


rule "SC:_Check_process"
	agenda-group "sc_check_destination"
    when
        component: DiagramPattern(destination instanceof Process)                    
    then
        drools.setFocus("sc_process");
end


rule "SC:_Check_external"
	agenda-group "sc_check_destination"
    when
        component: DiagramPattern(destination instanceof ExternalEntity)                    
    then
        drools.setFocus("sc_external");
end


rule "SC:_Check_datastore"
	agenda-group "sc_check_destination"
    when
        component: DiagramPattern(destination instanceof DataStore)                    
    then
        drools.setFocus("sc_datastore");
end


rule "SC_Process:_External"
	agenda-group "sc_process"
    when
     	DiagramPattern($list : traces)
     	traceElement : ElementTrace() from $list
     	Boolean(booleanValue == true) from traceElement.sourceElement instanceof ExternalEntity         
    then
        traceElement.addVulnerability(VulnerabilityCode.XSS);
end
