//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.model.risk_pattern.DiagramPiece;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import com.tas.codes.VulnerabilityCode;
import java.util.List;

//declare any global variables here


rule "Cross Site Request Forgery"
    when
        component: DiagramPiece(coreSource instanceof ExternalEntity,
        						coreDestination instanceof Process)                    
    then
        component.addVulnerability(VulnerabilityCode.INJECTION);
end


rule "Replay Attack"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof ExternalEntity)                    
    then
        component.addVulnerability(VulnerabilityCode.IDENTITY_SPOOOFING);
end


rule "Weak Credentials Storage"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof DataStore)                    
    then
        component.addVulnerability(VulnerabilityCode.PROGRAM_SPOOFING);
end


rule "Weak Access Control For A Resource"
    when
        component: DiagramPiece(coreSource instanceof DataStore, 
        						coreDestination instanceof Process)                    
    then
        component.addVulnerability(VulnerabilityCode.MEMORY_SAFETY);
end


rule "Iteration test rule"
    when    
     	component : DiagramPiece($list : coreDestinationFlowsIn)  
     	$value : Flow() from $list  
     	Boolean(booleanValue == true) from $value.source instanceof DataStore
    then
        component.addVulnerability(VulnerabilityCode.RACE_CONDITIONS);
end
