//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.*;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "Asset:_Admin_password"
    when
     	DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.ADMINISTRATOR_PASSWORD         
    then
        drools.setFocus("pii_check_request");	// identicna pravila za AP i PII
end
/*
rule "AP_Request:_Check_Confidentiality"
	agenda-group "ap_check_request"
    when
     	 DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.protectConfidentiality == true  
     then
        drools.setFocus("ap_check_primary");
end

rule "AP_Request:_Check_Availability"
	agenda-group "ap_check_request"
    when
     	DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.protectAvailability == true  
     then
        drools.setFocus("ap_check_primary");
end

rule "AP_Request:_Check_Integrity"
	agenda-group "ap_check_request"
    when
     	DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.protectIntegrity == true  
     then
        drools.setFocus("ap_check_primary");
end
*/
/* *************** CHECK VULNERABILITIES ****************/
/*
rule "AP:_Check_process"
	agenda-group "ap_check_primary"
    when
        DiagramPattern(element instanceof Process)                    
    then
        drools.setFocus("ap_process");
end

rule "AP:_Check_external"
	agenda-group "ap_check_primary"
    when
        DiagramPattern(element instanceof ExternalEntity)                    
    then
        drools.setFocus("ap_external");
end

rule "AP:_Check_datastore"
	agenda-group "ap_check_primary"
    when
        DiagramPattern(element instanceof DataStore)                    
    then
        drools.setFocus("ap_datastore");
end
*/

