//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.DiagramPiece;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "PII:_Forgery1"
    when
        component: DiagramPiece(coreDestination instanceof DataStore)                    
    then
        drools.setFocus("asset_pii");
end


rule "PII:_Forgery"
	agenda-group "asset_pii"
    when
        component: DiagramPiece(coreSource instanceof ExternalEntity,
        						coreDestination instanceof Process)                    
    then
        component.addVulnerability(VulnerabilityCode.RACE_CONDITIONS);
end


rule "PII:_Attack"
	agenda-group "asset_pii"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof ExternalEntity)                    
    then
        component.addVulnerability(VulnerabilityCode.RACE_CONDITIONS);
end


rule "PII:_Storage"
	agenda-group "asset_pii"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof DataStore)                    
    then
        component.addVulnerability(VulnerabilityCode.RACE_CONDITIONS);
end


rule "PII:_Resource"
	agenda-group "asset_pii"
    when
        component: DiagramPiece(coreSource instanceof DataStore, 
        						coreDestination instanceof Process)                    
    then
        component.addVulnerability(VulnerabilityCode.USER_INTERFACE);	// trebao bi i ovaj
end


rule "PII:_rule"
	agenda-group "asset_pii"
    when    
     	component : DiagramPiece($list : coreDestinationFlowsIn)  
     	$value : Flow() from $list  
     	Boolean(booleanValue == true) from $value.source instanceof DataStore
    then
        component.addVulnerability(VulnerabilityCode.RACE_CONDITIONS);
end
