//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.model.risk_pattern.DiagramPiece;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import com.tas.utils.ThreatCode;
import java.util.List;

//declare any global variables here


rule "Cross Site Request Forgery"
    when
        component: DiagramPiece(coreSource instanceof ExternalEntity,
        						coreDestination instanceof Process)                    
    then
        component.addThreat(ThreatCode.CSRF);
end


rule "Replay Attack"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof ExternalEntity)                    
    then
        component.addThreat(ThreatCode.REPLAY_ATTACK);
end


rule "Weak Credentials Storage"
    when
        component: DiagramPiece(coreSource instanceof Process, 
        						coreDestination instanceof DataStore)                    
    then
        component.addThreat(ThreatCode.WEAK_CREDENTIALS_STORAGE);
end


rule "Weak Access Control For A Resource"
    when
        component: DiagramPiece(coreSource instanceof DataStore, 
        						coreDestination instanceof Process)                    
    then
        component.addThreat(ThreatCode.WEAK_ACCESS_CONTROL_FOR_A_RESOURCE);
end


rule "Iteration test rule"
    when    
     	component : DiagramPiece($list : coreDestinationFlowsIn)  
     	$value : Flow() from $list  
     	Boolean(booleanValue == true) from $value.source instanceof DataStore
    then
        component.addThreat(ThreatCode.GO_GET_IT);
end
