//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.*;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "Asset:_Work_station"
    when
     	DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.WORK_STATION               
    then
        drools.setFocus("ws_check_destination");
end


rule "WS:_Check_process"
	agenda-group "ws_check_destination"
    when
        DiagramPattern(element instanceof Process)                    
    then
       	drools.setFocus("ws_process");
end


rule "WS:_Check_external"
	agenda-group "ws_check_destination"
    when
        DiagramPattern(element instanceof ExternalEntity)                    
    then
        drools.setFocus("ws_external");
end


rule "WS:_Check_datastore"
	agenda-group "ws_check_destination"
    when
        DiagramPattern(element instanceof DataStore)                    
    then
        drools.setFocus("ws_datastore");
end


rule "WS_Process:_Resource"
	agenda-group "ws_process"
    when
        traceElement: DiagramPattern(traceStart instanceof ExternalEntity)                  
    then
        traceElement.addVulnerability(VulnerabilityCode.NONE);
end
