//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import com.tas.codes.AssetCode;
import com.tas.codes.ExploitCode;
import com.tas.model.risk_pattern.*;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import com.tas.model.diagram.Diagram.Elements.SqlDatabase;
import com.tas.model.diagram.Diagram.Flows.Http;
import com.tas.model.diagram.Diagram.Elements.Browser;
import java.util.List;

//declare any global variables here


rule "Asset:_Work_station"
    when
     	pattern : DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.WORK_STATION
     	
     	Boolean(booleanValue == true) from pattern.element.runLevel == "HIGH_PRIVILEGE"  
    then
        drools.setFocus("ws_check_request");
end

rule "WS_Request:_Check_Resource_Aspects"
	agenda-group "ws_check_request"
    when
     	 DiagramPattern($list : assets)  
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.protectConfidentiality == true or
     	Boolean(booleanValue == true) from $value.protectAvailability == true or
     	Boolean(booleanValue == true) from $value.protectIntegrity == true
     then
        drools.setFocus("ws_check_primary");
end

/* *************** CHECK EXPLOITS	 	****************/

rule "WS:_Check_process"
	agenda-group "ws_check_primary"
    when
        pattern : DiagramPattern(element instanceof Process)                    
    then
        pattern.addExploitAndAsset(ExploitCode.ELEVATION_OF_PRIVILEGE, AssetCode.WORK_STATION);	// pretpostavimo da ce postojati ukoliko imamo proces 
       	drools.setFocus("ws_process");
end


rule "WS:_Check_external"
	agenda-group "ws_check_primary"
    when
        pattern : DiagramPattern(element instanceof ExternalEntity)                    
    then
        drools.setFocus("ws_external");
end

rule "WS:_Check_external_browser"
	agenda-group "sc_check_primary"
    when
        pattern : DiagramPattern(element instanceof Browser)                             
    then
        pattern.addExploitAndAsset(ExploitCode.XSS, AssetCode.WORK_STATION);	// pretpostavimo da XSS postoji svaki put kada podaci idu ka Ext.Ent.
        drools.setFocus("ws_external");
end

rule "WS:_Check_datastore"
	agenda-group "ws_check_primary"
    when
        DiagramPattern(element instanceof DataStore)                    
    then
        drools.setFocus("ws_datastore");
end

rule "WS:_Check_Confidentiality_for_Session_Hijack"
	agenda-group "ws_check_primary"			// ako je prenos podataka otvoren, mogu se procitati kredencijali ili cookie, pomocu cega se moze ukrasi sesija
    when									// nije ukljuceno u prethodno pravilo, posto ona zahteva da se stiti confidentality
     	pattern : DiagramPattern($list : trace)
     	elementInTrace : Element() from $list
     	DiagramPattern(elementInTrace instanceof Http) 
    then
        pattern.addExploitAndAsset(ExploitCode.SESSION_HIJACK, AssetCode.WORK_STATION);
end


rule "WS_Datastore:_SQL_Database"
	agenda-group "ws_datastore"
    when
        pattern: DiagramPattern(element instanceof SqlDatabase)                  
    then
        pattern.addExploitAndAsset(ExploitCode.INJECTION_SQL, AssetCode.WORK_STATION);	// pretpostavimo da XML Injection postoji svaki put kada podaci idu ka SQL bazi
        drools.setFocus("ws_datastore_remove_potential_injection");
end

rule "WS_Datastore:_Encrypting"
	agenda-group "ws_datastore"
    when
     	pattern : DiagramPattern()  
		Boolean(booleanValue == true) from ((DataStore)pattern.element).dataIsEncrypted == false
		Boolean(booleanValue == true) from ((DataStore)pattern.element).storeCredentials == false                
    then
        pattern.addExploitAndAsset(ExploitCode.SESSION_HIJACK, AssetCode.WORK_STATION);
end

rule "WS_Datastore:_SQL_Database_Remove_injection"
	agenda-group "ws_datastore_remove_potential_injection"
    when
        pattern : DiagramPattern(traceStart instanceof Process)      
     	DiagramPattern($list : trace)
     	elementInTrace : Element() from $list
     	Boolean(booleanValue == true) from elementInTrace instanceof Process  
     	Boolean(booleanValue == true) from ((Process)elementInTrace).sanitizeInput == false                
    then
        pattern.removeExploitAndAsset(ExploitCode.INJECTION_SQL);
end


rule "WS_External:_Process_XSS"
	agenda-group "ws_external"
    when
        pattern : DiagramPattern(traceStart instanceof Process)      
     	DiagramPattern($list : trace)
     	elementInTrace : Element() from $list
     	Boolean(booleanValue == true) from elementInTrace instanceof Process  
     	Boolean(booleanValue == true) from ((Process)elementInTrace).sanitizeOutput == false
    then
        pattern.removeExploitAndAsset(ExploitCode.XSS);
end


rule "WS_Process:_Session_Timeout1"	// ako se sesija ne tajmautuje, moguce je pogoditi njen ID pa ga iskoristiti
	agenda-group "ws_process"
    when
     	pattern : DiagramPattern()
		Boolean(booleanValue == true) from ((Process)pattern.element).sessionHasTimeouts == false
    then
        pattern.addExploitAndAsset(ExploitCode.SESSION_HIJACK, AssetCode.WORK_STATION);
end

rule "WS_Process:_Check_Access_Controll"	// ako se sesija ne tajmautuje, moguce je pogoditi njen ID pa ga iskoristiti
	agenda-group "ws_process"
    when
     	pattern : DiagramPattern()
     	
		Boolean(booleanValue == true) from ((Process)pattern.element).requiresAuthentication == true
		Boolean(booleanValue == true) from ((Process)pattern.element).requiresAuthorization == true
    then
        pattern.removeExploitAndAsset(ExploitCode.ELEVATION_OF_PRIVILEGE);
end
