//created on: Jun 6, 2017
package com.tas.rules

//list any import classes here.
import javax.xml.bind.JAXBElement;
import com.tas.codes.AssetCode;
import com.tas.codes.VulnerabilityCode;
import com.tas.model.risk_pattern.*;
import com.tas.model.diagram.Process;
import com.tas.model.diagram.*;
import java.util.List;

//declare any global variables here


rule "Asset:_PII"
    when    
     	DiagramPattern($list : assets)
     	$value : AssetDefinition() from $list  
     	Boolean(booleanValue == true) from $value.assetId == AssetCode.PII 
    then
        drools.setFocus("pii_check_destination");
end


rule "PII:_Check_process"
	agenda-group "pii_check_destination"
    when
        DiagramPattern(element instanceof Process)                    
    then
        drools.setFocus("pii_process");
end


rule "PII:_Check_external"
	agenda-group "pii_check_destination"
    when
        DiagramPattern(element instanceof ExternalEntity)                    
    then
        drools.setFocus("pii_external");
end


rule "PII:_Check_datastore"
	agenda-group "pii_check_destination"
    when
        DiagramPattern(element instanceof DataStore)                    
    then
        drools.setFocus("pii_datastore");
end


rule "PII_Process:_External"
	agenda-group "pii_process"
    when
        traceElement: DiagramPattern(traceStart instanceof ExternalEntity)                  
    then
        traceElement.addVulnerability(VulnerabilityCode.NONE);
end
