//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 09:53:02 AM CEST 
//


package com.tas.model.diagram;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for assetDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assetDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="assetId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="assetTitle" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="44"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="protectConfidentiality" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="protectIntegrity" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="protectAvailability" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="impactConfidentiality" use="required" type="{https://www.tas.org/tas-schemas}impactType" />
 *       &lt;attribute name="impactIntegrity" use="required" type="{https://www.tas.org/tas-schemas}impactType" />
 *       &lt;attribute name="impactAvailability" use="required" type="{https://www.tas.org/tas-schemas}impactType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assetDefinition")
public class AssetDefinition {

    @XmlAttribute(name = "assetId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String assetId;
    @XmlAttribute(name = "assetTitle", required = true)
    protected String assetTitle;
    @XmlAttribute(name = "protectConfidentiality", required = true)
    protected boolean protectConfidentiality;
    @XmlAttribute(name = "protectIntegrity", required = true)
    protected boolean protectIntegrity;
    @XmlAttribute(name = "protectAvailability", required = true)
    protected boolean protectAvailability;
    @XmlAttribute(name = "impactConfidentiality", required = true)
    protected int impactConfidentiality;
    @XmlAttribute(name = "impactIntegrity", required = true)
    protected int impactIntegrity;
    @XmlAttribute(name = "impactAvailability", required = true)
    protected int impactAvailability;

    /**
     * Gets the value of the assetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * Sets the value of the assetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetId(String value) {
        this.assetId = value;
    }

    /**
     * Gets the value of the assetTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetTitle() {
        return assetTitle;
    }

    /**
     * Sets the value of the assetTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetTitle(String value) {
        this.assetTitle = value;
    }

    /**
     * Gets the value of the protectConfidentiality property.
     * 
     */
    public boolean isProtectConfidentiality() {
        return protectConfidentiality;
    }

    /**
     * Sets the value of the protectConfidentiality property.
     * 
     */
    public void setProtectConfidentiality(boolean value) {
        this.protectConfidentiality = value;
    }

    /**
     * Gets the value of the protectIntegrity property.
     * 
     */
    public boolean isProtectIntegrity() {
        return protectIntegrity;
    }

    /**
     * Sets the value of the protectIntegrity property.
     * 
     */
    public void setProtectIntegrity(boolean value) {
        this.protectIntegrity = value;
    }

    /**
     * Gets the value of the protectAvailability property.
     * 
     */
    public boolean isProtectAvailability() {
        return protectAvailability;
    }

    /**
     * Sets the value of the protectAvailability property.
     * 
     */
    public void setProtectAvailability(boolean value) {
        this.protectAvailability = value;
    }

    /**
     * Gets the value of the impactConfidentiality property.
     * 
     */
    public int getImpactConfidentiality() {
        return impactConfidentiality;
    }

    /**
     * Sets the value of the impactConfidentiality property.
     * 
     */
    public void setImpactConfidentiality(int value) {
        this.impactConfidentiality = value;
    }

    /**
     * Gets the value of the impactIntegrity property.
     * 
     */
    public int getImpactIntegrity() {
        return impactIntegrity;
    }

    /**
     * Sets the value of the impactIntegrity property.
     * 
     */
    public void setImpactIntegrity(int value) {
        this.impactIntegrity = value;
    }

    /**
     * Gets the value of the impactAvailability property.
     * 
     */
    public int getImpactAvailability() {
        return impactAvailability;
    }

    /**
     * Sets the value of the impactAvailability property.
     * 
     */
    public void setImpactAvailability(int value) {
        this.impactAvailability = value;
    }

}
