//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 11:52:42 AM CEST 
//


package com.tas.model.diagram;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assets complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assets">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asset" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="assetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="protectConfidentiality" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="protectIntegrity " type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="protectAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assets", propOrder = {
    "asset"
})
public class Assets {

    @XmlElement(required = true)
    protected List<Assets.Asset> asset;

    /**
     * Gets the value of the asset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the asset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAsset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Assets.Asset }
     * 
     * 
     */
    public List<Assets.Asset> getAsset() {
        if (asset == null) {
            asset = new ArrayList<Assets.Asset>();
        }
        return this.asset;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="assetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="protectConfidentiality" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="protectIntegrity " type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="protectAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Asset {

        @XmlAttribute(name = "assetId", required = true)
        protected String assetId;
        @XmlAttribute(name = "protectConfidentiality")
        protected Boolean protectConfidentiality;
        @XmlAttribute(name = "protectIntegrity ")
        protected Boolean protectIntegrity0020;
        @XmlAttribute(name = "protectAvailability")
        protected Boolean protectAvailability;

        /**
         * Gets the value of the assetId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssetId() {
            return assetId;
        }

        /**
         * Sets the value of the assetId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssetId(String value) {
            this.assetId = value;
        }

        /**
         * Gets the value of the protectConfidentiality property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isProtectConfidentiality() {
            if (protectConfidentiality == null) {
                return false;
            } else {
                return protectConfidentiality;
            }
        }

        /**
         * Sets the value of the protectConfidentiality property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setProtectConfidentiality(Boolean value) {
            this.protectConfidentiality = value;
        }

        /**
         * Gets the value of the protectIntegrity0020 property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isProtectIntegrity_0020() {
            if (protectIntegrity0020 == null) {
                return false;
            } else {
                return protectIntegrity0020;
            }
        }

        /**
         * Sets the value of the protectIntegrity0020 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setProtectIntegrity_0020(Boolean value) {
            this.protectIntegrity0020 = value;
        }

        /**
         * Gets the value of the protectAvailability property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isProtectAvailability() {
            if (protectAvailability == null) {
                return false;
            } else {
                return protectAvailability;
            }
        }

        /**
         * Sets the value of the protectAvailability property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setProtectAvailability(Boolean value) {
            this.protectAvailability = value;
        }

    }

}
