//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.21 at 11:52:42 AM CEST 
//


package com.tas.model.diagram;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="element">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.tas.org/tas-schemas}base">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="threats" type="{https://www.tas.org/tas-schemas}threats" form="qualified"/>
 *       &lt;/sequence>
 *       &lt;attribute name="outOfScope" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="outOfScopeReason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "element", propOrder = {
    "threats"
})
@XmlSeeAlso({
    BlockElement.class,
    OriginalFlow.class
})
public abstract class Element
    extends Base
{

    protected Threats threats;
    @XmlAttribute(name = "outOfScope")
    protected Boolean outOfScope;
    @XmlAttribute(name = "outOfScopeReason")
    protected String outOfScopeReason;

    /**
     * Gets the value of the threats property.
     * 
     * @return
     *     possible object is
     *     {@link Threats }
     *     
     */
    public Threats getThreats() {
        return threats;
    }

    /**
     * Sets the value of the threats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Threats }
     *     
     */
    public void setThreats(Threats value) {
        this.threats = value;
    }

    /**
     * Gets the value of the outOfScope property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOutOfScope() {
        if (outOfScope == null) {
            return false;
        } else {
            return outOfScope;
        }
    }

    /**
     * Sets the value of the outOfScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOutOfScope(Boolean value) {
        this.outOfScope = value;
    }

    /**
     * Gets the value of the outOfScopeReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOfScopeReason() {
        return outOfScopeReason;
    }

    /**
     * Sets the value of the outOfScopeReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOfScopeReason(String value) {
        this.outOfScopeReason = value;
    }

}
