//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 08:30:42 AM CEST 
//

package com.tas.model.diagram;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flow complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flow">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.tas.org/diagram-schema}element">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="boundaryCross">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="boundary" use="required" type="{https://www.tas.org/diagram-schema}typeIdRef" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="source" use="required" type="{https://www.tas.org/diagram-schema}typeIdRef" />
 *       &lt;attribute name="destination" use="required" type="{https://www.tas.org/diagram-schema}typeIdRef" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flow", propOrder = {
    "boundaryCross"
})
@XmlSeeAlso({
	com.tas.model.diagram.Diagram.Flows.CustomFlow.class
})
public class Flow
    extends Element
{

    protected List<Flow.BoundaryCross> boundaryCross;
    @XmlAttribute(name = "source", required = true)
    @XmlIDREF
    protected Object source;
    @XmlAttribute(name = "destination", required = true)
    @XmlIDREF
    protected Object destination;

    /**
     * Gets the value of the boundaryCross property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boundaryCross property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoundaryCross().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Flow.BoundaryCross }
     * 
     * 
     */
    public List<Flow.BoundaryCross> getBoundaryCross() {
        if (boundaryCross == null) {
            boundaryCross = new ArrayList<Flow.BoundaryCross>();
        }
        return this.boundaryCross;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSource(Object value) {
        this.source = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDestination(Object value) {
        this.destination = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="boundary" use="required" type="{https://www.tas.org/diagram-schema}typeIdRef" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BoundaryCross {

        @XmlAttribute(name = "boundary", required = true)
        @XmlIDREF
        protected Object boundary;

        /**
         * Gets the value of the boundary property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getBoundary() {
            return boundary;
        }

        /**
         * Sets the value of the boundary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setBoundary(Object value) {
            this.boundary = value;
        }

    }

}
