//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 01:21:34 PM CEST 
//


package com.tas.model.diagram;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tas.model.diagram package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DiagramShapesAppContainerBoundary_QNAME = new QName("https://www.tas.org/diagram-schema", "appContainerBoundary");
    private final static QName _DiagramShapesOtherTrustSection_QNAME = new QName("https://www.tas.org/diagram-schema", "otherTrustSection");
    private final static QName _DiagramShapesCompanyTrustSection_QNAME = new QName("https://www.tas.org/diagram-schema", "companyTrustSection");
    private final static QName _DiagramShapesLocalDMZBoundary_QNAME = new QName("https://www.tas.org/diagram-schema", "localDMZBoundary");
    private final static QName _DiagramShapesInternetBoundary_QNAME = new QName("https://www.tas.org/diagram-schema", "internetBoundary");
    private final static QName _DiagramShapesInternetDmz_QNAME = new QName("https://www.tas.org/diagram-schema", "internetDmz");
    private final static QName _DiagramShapesSandboxTrustSection_QNAME = new QName("https://www.tas.org/diagram-schema", "sandboxTrustSection");
    private final static QName _DiagramShapesSharedNetwork_QNAME = new QName("https://www.tas.org/diagram-schema", "sharedNetwork");
    private final static QName _DiagramShapesMachineBoundary_QNAME = new QName("https://www.tas.org/diagram-schema", "machineBoundary");
    private final static QName _DiagramShapesOfficeNetwork_QNAME = new QName("https://www.tas.org/diagram-schema", "officeNetwork");
    private final static QName _DiagramElementsSqlDatabase_QNAME = new QName("https://www.tas.org/diagram-schema", "sqlDatabase");
    private final static QName _DiagramElementsFileSystem_QNAME = new QName("https://www.tas.org/diagram-schema", "fileSystem");
    private final static QName _DiagramElementsHtml5LocalStorage_QNAME = new QName("https://www.tas.org/diagram-schema", "html5LocalStorage");
    private final static QName _DiagramElementsCache_QNAME = new QName("https://www.tas.org/diagram-schema", "cache");
    private final static QName _DiagramElementsSecurityGateway_QNAME = new QName("https://www.tas.org/diagram-schema", "securityGateway");
    private final static QName _DiagramElementsWebApplication_QNAME = new QName("https://www.tas.org/diagram-schema", "webApplication");
    private final static QName _DiagramElementsCustomExternalEntities_QNAME = new QName("https://www.tas.org/diagram-schema", "customExternalEntities");
    private final static QName _DiagramElementsSmartPhone_QNAME = new QName("https://www.tas.org/diagram-schema", "smartPhone");
    private final static QName _DiagramElementsWebServer_QNAME = new QName("https://www.tas.org/diagram-schema", "webServer");
    private final static QName _DiagramElementsThickClient_QNAME = new QName("https://www.tas.org/diagram-schema", "thickClient");
    private final static QName _DiagramElementsCustomDataStore_QNAME = new QName("https://www.tas.org/diagram-schema", "customDataStore");
    private final static QName _DiagramElementsExternalWebApplication_QNAME = new QName("https://www.tas.org/diagram-schema", "externalWebApplication");
    private final static QName _DiagramElementsSpecialApplication_QNAME = new QName("https://www.tas.org/diagram-schema", "specialApplication");
    private final static QName _DiagramElementsCloudStorage_QNAME = new QName("https://www.tas.org/diagram-schema", "cloudStorage");
    private final static QName _DiagramElementsNoSqlDatabase_QNAME = new QName("https://www.tas.org/diagram-schema", "noSqlDatabase");
    private final static QName _DiagramElementsCustomProcess_QNAME = new QName("https://www.tas.org/diagram-schema", "customProcess");
    private final static QName _DiagramElementsWebService_QNAME = new QName("https://www.tas.org/diagram-schema", "webService");
    private final static QName _DiagramElementsExternalWebService_QNAME = new QName("https://www.tas.org/diagram-schema", "externalWebService");
    private final static QName _DiagramElementsConfigurationFile_QNAME = new QName("https://www.tas.org/diagram-schema", "configurationFile");
    private final static QName _DiagramElementsLogFile_QNAME = new QName("https://www.tas.org/diagram-schema", "logFile");
    private final static QName _DiagramElementsBrowser_QNAME = new QName("https://www.tas.org/diagram-schema", "browser");
    private final static QName _DiagramElementsAuthorizedProvider_QNAME = new QName("https://www.tas.org/diagram-schema", "authorizedProvider");
    private final static QName _DiagramElementsManagedApplication_QNAME = new QName("https://www.tas.org/diagram-schema", "managedApplication");
    private final static QName _DiagramElementsUser_QNAME = new QName("https://www.tas.org/diagram-schema", "user");
    private final static QName _DiagramFlowsTcp_QNAME = new QName("https://www.tas.org/diagram-schema", "tcp");
    private final static QName _DiagramFlowsUdp_QNAME = new QName("https://www.tas.org/diagram-schema", "udp");
    private final static QName _DiagramFlowsIpSec_QNAME = new QName("https://www.tas.org/diagram-schema", "ipSec");
    private final static QName _DiagramFlowsNamedPipe_QNAME = new QName("https://www.tas.org/diagram-schema", "namedPipe");
    private final static QName _DiagramFlowsBinary_QNAME = new QName("https://www.tas.org/diagram-schema", "binary");
    private final static QName _DiagramFlowsHttp_QNAME = new QName("https://www.tas.org/diagram-schema", "http");
    private final static QName _DiagramFlowsSmb_QNAME = new QName("https://www.tas.org/diagram-schema", "smb");
    private final static QName _DiagramFlowsHttps_QNAME = new QName("https://www.tas.org/diagram-schema", "https");
    private final static QName _DiagramFlowsSsl_QNAME = new QName("https://www.tas.org/diagram-schema", "ssl");
    private final static QName _DiagramFlowsCustomFlow_QNAME = new QName("https://www.tas.org/diagram-schema", "customFlow");
    private final static QName _DiagramFlowsRpcOrDcom_QNAME = new QName("https://www.tas.org/diagram-schema", "rpcOrDcom");
    private final static QName _DiagramFlowsSql_QNAME = new QName("https://www.tas.org/diagram-schema", "sql");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tas.model.diagram
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Diagram }
     * 
     */
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link Diagram.Flows }
     * 
     */
    public Diagram.Flows createDiagramFlows() {
        return new Diagram.Flows();
    }

    /**
     * Create an instance of {@link Diagram.Elements }
     * 
     */
    public Diagram.Elements createDiagramElements() {
        return new Diagram.Elements();
    }

    /**
     * Create an instance of {@link Diagram.Shapes }
     * 
     */
    public Diagram.Shapes createDiagramShapes() {
        return new Diagram.Shapes();
    }

    /**
     * Create an instance of {@link CustomAttribute }
     * 
     */
    public CustomAttribute createCustomAttribute() {
        return new CustomAttribute();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link BlockShape }
     * 
     */
    public BlockShape createBlockShape() {
        return new BlockShape();
    }

    /**
     * Create an instance of {@link ExternalEntity }
     * 
     */
    public ExternalEntity createExternalEntity() {
        return new ExternalEntity();
    }

    /**
     * Create an instance of {@link DataStore }
     * 
     */
    public DataStore createDataStore() {
        return new DataStore();
    }

    /**
     * Create an instance of {@link Flow.BoundaryCross }
     * 
     */
    public Flow.BoundaryCross createFlowBoundaryCross() {
        return new Flow.BoundaryCross();
    }

    /**
     * Create an instance of {@link Diagram.Flows.CustomFlow }
     * 
     */
    public Diagram.Flows.CustomFlow createDiagramFlowsCustomFlow() {
        return new Diagram.Flows.CustomFlow();
    }

    /**
     * Create an instance of {@link Diagram.Elements.CustomProcess }
     * 
     */
    public Diagram.Elements.CustomProcess createDiagramElementsCustomProcess() {
        return new Diagram.Elements.CustomProcess();
    }

    /**
     * Create an instance of {@link Diagram.Elements.CustomExternalEntities }
     * 
     */
    public Diagram.Elements.CustomExternalEntities createDiagramElementsCustomExternalEntities() {
        return new Diagram.Elements.CustomExternalEntities();
    }

    /**
     * Create an instance of {@link Diagram.Elements.CustomDataStore }
     * 
     */
    public Diagram.Elements.CustomDataStore createDiagramElementsCustomDataStore() {
        return new Diagram.Elements.CustomDataStore();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "appContainerBoundary", scope = Diagram.Shapes.class)
    public JAXBElement<Shape> createDiagramShapesAppContainerBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramShapesAppContainerBoundary_QNAME, Shape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "otherTrustSection", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesOtherTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesOtherTrustSection_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "companyTrustSection", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesCompanyTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesCompanyTrustSection_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "localDMZBoundary", scope = Diagram.Shapes.class)
    public JAXBElement<Shape> createDiagramShapesLocalDMZBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramShapesLocalDMZBoundary_QNAME, Shape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "internetBoundary", scope = Diagram.Shapes.class)
    public JAXBElement<Shape> createDiagramShapesInternetBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramShapesInternetBoundary_QNAME, Shape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "internetDmz", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesInternetDmz(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesInternetDmz_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "sandboxTrustSection", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesSandboxTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesSandboxTrustSection_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "sharedNetwork", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesSharedNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesSharedNetwork_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "machineBoundary", scope = Diagram.Shapes.class)
    public JAXBElement<Shape> createDiagramShapesMachineBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramShapesMachineBoundary_QNAME, Shape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "officeNetwork", scope = Diagram.Shapes.class)
    public JAXBElement<BlockShape> createDiagramShapesOfficeNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramShapesOfficeNetwork_QNAME, BlockShape.class, Diagram.Shapes.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "sqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsSqlDatabase(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsSqlDatabase_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "fileSystem", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsFileSystem(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsFileSystem_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "html5LocalStorage", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsHtml5LocalStorage(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsHtml5LocalStorage_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "cache", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsCache(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsCache_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "securityGateway", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSecurityGateway(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSecurityGateway_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "webApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.CustomExternalEntities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "customExternalEntities", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.CustomExternalEntities> createDiagramElementsCustomExternalEntities(Diagram.Elements.CustomExternalEntities value) {
        return new JAXBElement<Diagram.Elements.CustomExternalEntities>(_DiagramElementsCustomExternalEntities_QNAME, Diagram.Elements.CustomExternalEntities.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "smartPhone", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSmartPhone(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSmartPhone_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "webServer", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebServer(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebServer_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "thickClient", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsThickClient(Process value) {
        return new JAXBElement<Process>(_DiagramElementsThickClient_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.CustomDataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "customDataStore", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.CustomDataStore> createDiagramElementsCustomDataStore(Diagram.Elements.CustomDataStore value) {
        return new JAXBElement<Diagram.Elements.CustomDataStore>(_DiagramElementsCustomDataStore_QNAME, Diagram.Elements.CustomDataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "externalWebApplication", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsExternalWebApplication(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsExternalWebApplication_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "specialApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsSpecialApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsSpecialApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "cloudStorage", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsCloudStorage(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsCloudStorage_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "noSqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsNoSqlDatabase(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsNoSqlDatabase_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Elements.CustomProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "customProcess", scope = Diagram.Elements.class)
    public JAXBElement<Diagram.Elements.CustomProcess> createDiagramElementsCustomProcess(Diagram.Elements.CustomProcess value) {
        return new JAXBElement<Diagram.Elements.CustomProcess>(_DiagramElementsCustomProcess_QNAME, Diagram.Elements.CustomProcess.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "webService", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebService(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebService_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "externalWebService", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsExternalWebService(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsExternalWebService_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "configurationFile", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsConfigurationFile(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsConfigurationFile_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "logFile", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsLogFile(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsLogFile_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "browser", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsBrowser(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsBrowser_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "authorizedProvider", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsAuthorizedProvider(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsAuthorizedProvider_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "managedApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsManagedApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsManagedApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "user", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsUser(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsUser_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "tcp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsTcp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsTcp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "udp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsUdp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsUdp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "ipSec", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsIpSec(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsIpSec_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "namedPipe", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsNamedPipe(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsNamedPipe_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "binary", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsBinary(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsBinary_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "http", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsHttp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsHttp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "smb", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSmb(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSmb_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "https", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsHttps(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsHttps_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "ssl", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSsl(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSsl_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diagram.Flows.CustomFlow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "customFlow", scope = Diagram.Flows.class)
    public JAXBElement<Diagram.Flows.CustomFlow> createDiagramFlowsCustomFlow(Diagram.Flows.CustomFlow value) {
        return new JAXBElement<Diagram.Flows.CustomFlow>(_DiagramFlowsCustomFlow_QNAME, Diagram.Flows.CustomFlow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "rpcOrDcom", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsRpcOrDcom(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsRpcOrDcom_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/diagram-schema", name = "sql", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSql(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSql_QNAME, Flow.class, Diagram.Flows.class, value);
    }

}
