//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 12:39:35 PM CEST 
//


package com.tas.model.diagram;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tas.model.diagram package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DiagramBoundariesAppContainerBoundary_QNAME = new QName("https://www.tas.org/tas-schemas", "appContainerBoundary");
    private final static QName _DiagramBoundariesLocalDMZBoundary_QNAME = new QName("https://www.tas.org/tas-schemas", "localDMZBoundary");
    private final static QName _DiagramBoundariesInternetBoundary_QNAME = new QName("https://www.tas.org/tas-schemas", "internetBoundary");
    private final static QName _DiagramBoundariesMachineBoundary_QNAME = new QName("https://www.tas.org/tas-schemas", "machineBoundary");
    private final static QName _DiagramElementsFileSystem_QNAME = new QName("https://www.tas.org/tas-schemas", "fileSystem");
    private final static QName _DiagramElementsHtml5LocalStorage_QNAME = new QName("https://www.tas.org/tas-schemas", "html5LocalStorage");
    private final static QName _DiagramElementsSqlDatabase_QNAME = new QName("https://www.tas.org/tas-schemas", "sqlDatabase");
    private final static QName _DiagramElementsSecurityGateway_QNAME = new QName("https://www.tas.org/tas-schemas", "securityGateway");
    private final static QName _DiagramElementsCache_QNAME = new QName("https://www.tas.org/tas-schemas", "cache");
    private final static QName _DiagramElementsWebApplication_QNAME = new QName("https://www.tas.org/tas-schemas", "webApplication");
    private final static QName _DiagramElementsWebServer_QNAME = new QName("https://www.tas.org/tas-schemas", "webServer");
    private final static QName _DiagramElementsThickClient_QNAME = new QName("https://www.tas.org/tas-schemas", "thickClient");
    private final static QName _DiagramElementsSmartPhone_QNAME = new QName("https://www.tas.org/tas-schemas", "smartPhone");
    private final static QName _DiagramElementsSpecialApplication_QNAME = new QName("https://www.tas.org/tas-schemas", "specialApplication");
    private final static QName _DiagramElementsExternalWebApplication_QNAME = new QName("https://www.tas.org/tas-schemas", "externalWebApplication");
    private final static QName _DiagramElementsCloudStorage_QNAME = new QName("https://www.tas.org/tas-schemas", "cloudStorage");
    private final static QName _DiagramElementsNoSqlDatabase_QNAME = new QName("https://www.tas.org/tas-schemas", "noSqlDatabase");
    private final static QName _DiagramElementsWebService_QNAME = new QName("https://www.tas.org/tas-schemas", "webService");
    private final static QName _DiagramElementsExternalWebService_QNAME = new QName("https://www.tas.org/tas-schemas", "externalWebService");
    private final static QName _DiagramElementsConfigurationFile_QNAME = new QName("https://www.tas.org/tas-schemas", "configurationFile");
    private final static QName _DiagramElementsLogFile_QNAME = new QName("https://www.tas.org/tas-schemas", "logFile");
    private final static QName _DiagramElementsBrowser_QNAME = new QName("https://www.tas.org/tas-schemas", "browser");
    private final static QName _DiagramElementsAuthorizedProvider_QNAME = new QName("https://www.tas.org/tas-schemas", "authorizedProvider");
    private final static QName _DiagramElementsManagedApplication_QNAME = new QName("https://www.tas.org/tas-schemas", "managedApplication");
    private final static QName _DiagramElementsUser_QNAME = new QName("https://www.tas.org/tas-schemas", "user");
    private final static QName _StringAndLinkLink_QNAME = new QName("https://www.tas.org/tas-schemas", "link");
    private final static QName _DiagramFlowsIpSec_QNAME = new QName("https://www.tas.org/tas-schemas", "ipSec");
    private final static QName _DiagramFlowsTcp_QNAME = new QName("https://www.tas.org/tas-schemas", "tcp");
    private final static QName _DiagramFlowsUdp_QNAME = new QName("https://www.tas.org/tas-schemas", "udp");
    private final static QName _DiagramFlowsBinary_QNAME = new QName("https://www.tas.org/tas-schemas", "binary");
    private final static QName _DiagramFlowsNamedPipe_QNAME = new QName("https://www.tas.org/tas-schemas", "namedPipe");
    private final static QName _DiagramFlowsHttp_QNAME = new QName("https://www.tas.org/tas-schemas", "http");
    private final static QName _DiagramFlowsSmb_QNAME = new QName("https://www.tas.org/tas-schemas", "smb");
    private final static QName _DiagramFlowsHttps_QNAME = new QName("https://www.tas.org/tas-schemas", "https");
    private final static QName _DiagramFlowsSsl_QNAME = new QName("https://www.tas.org/tas-schemas", "ssl");
    private final static QName _DiagramFlowsSql_QNAME = new QName("https://www.tas.org/tas-schemas", "sql");
    private final static QName _DiagramFlowsRpcOrDcom_QNAME = new QName("https://www.tas.org/tas-schemas", "rpcOrDcom");
    private final static QName _DiagramSectionsOtherTrustSection_QNAME = new QName("https://www.tas.org/tas-schemas", "otherTrustSection");
    private final static QName _DiagramSectionsCompanyTrustSection_QNAME = new QName("https://www.tas.org/tas-schemas", "companyTrustSection");
    private final static QName _DiagramSectionsInternetDmz_QNAME = new QName("https://www.tas.org/tas-schemas", "internetDmz");
    private final static QName _DiagramSectionsSandboxTrustSection_QNAME = new QName("https://www.tas.org/tas-schemas", "sandboxTrustSection");
    private final static QName _DiagramSectionsSharedNetwork_QNAME = new QName("https://www.tas.org/tas-schemas", "sharedNetwork");
    private final static QName _DiagramSectionsOfficeNetwork_QNAME = new QName("https://www.tas.org/tas-schemas", "officeNetwork");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tas.model.diagram
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Diagram }
     * 
     */
    public Diagram createDiagram() {
        return new Diagram();
    }

    /**
     * Create an instance of {@link OriginalFlow }
     * 
     */
    public OriginalFlow createOriginalFlow() {
        return new OriginalFlow();
    }

    /**
     * Create an instance of {@link OriginalFlow.BoundariesCrossed }
     * 
     */
    public OriginalFlow.BoundariesCrossed createOriginalFlowBoundariesCrossed() {
        return new OriginalFlow.BoundariesCrossed();
    }

    /**
     * Create an instance of {@link Vulnerabilities }
     * 
     */
    public Vulnerabilities createVulnerabilities() {
        return new Vulnerabilities();
    }

    /**
     * Create an instance of {@link Assets }
     * 
     */
    public Assets createAssets() {
        return new Assets();
    }

    /**
     * Create an instance of {@link StringAndLink }
     * 
     */
    public StringAndLink createStringAndLink() {
        return new StringAndLink();
    }

    /**
     * Create an instance of {@link Diagram.Elements }
     * 
     */
    public Diagram.Elements createDiagramElements() {
        return new Diagram.Elements();
    }

    /**
     * Create an instance of {@link Diagram.Flows }
     * 
     */
    public Diagram.Flows createDiagramFlows() {
        return new Diagram.Flows();
    }

    /**
     * Create an instance of {@link Diagram.Boundaries }
     * 
     */
    public Diagram.Boundaries createDiagramBoundaries() {
        return new Diagram.Boundaries();
    }

    /**
     * Create an instance of {@link Diagram.Sections }
     * 
     */
    public Diagram.Sections createDiagramSections() {
        return new Diagram.Sections();
    }

    /**
     * Create an instance of {@link VulnerabilitiesDefinitions }
     * 
     */
    public VulnerabilitiesDefinitions createVulnerabilitiesDefinitions() {
        return new VulnerabilitiesDefinitions();
    }

    /**
     * Create an instance of {@link VulnerabilityDefinition }
     * 
     */
    public VulnerabilityDefinition createVulnerabilityDefinition() {
        return new VulnerabilityDefinition();
    }

    /**
     * Create an instance of {@link AssetDefinitions }
     * 
     */
    public AssetDefinitions createAssetDefinitions() {
        return new AssetDefinitions();
    }

    /**
     * Create an instance of {@link AssetDefinition }
     * 
     */
    public AssetDefinition createAssetDefinition() {
        return new AssetDefinition();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link ImportAssets }
     * 
     */
    public ImportAssets createImportAssets() {
        return new ImportAssets();
    }

    /**
     * Create an instance of {@link ImportVulnerabilities }
     * 
     */
    public ImportVulnerabilities createImportVulnerabilities() {
        return new ImportVulnerabilities();
    }

    /**
     * Create an instance of {@link BlockShape }
     * 
     */
    public BlockShape createBlockShape() {
        return new BlockShape();
    }

    /**
     * Create an instance of {@link ExternalEntity }
     * 
     */
    public ExternalEntity createExternalEntity() {
        return new ExternalEntity();
    }

    /**
     * Create an instance of {@link DataStore }
     * 
     */
    public DataStore createDataStore() {
        return new DataStore();
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link OriginalFlow.BoundariesCrossed.BoundaryCross }
     * 
     */
    public OriginalFlow.BoundariesCrossed.BoundaryCross createOriginalFlowBoundariesCrossedBoundaryCross() {
        return new OriginalFlow.BoundariesCrossed.BoundaryCross();
    }

    /**
     * Create an instance of {@link OriginalDataStore }
     * 
     */
    public OriginalDataStore createOriginalDataStore() {
        return new OriginalDataStore();
    }

    /**
     * Create an instance of {@link Vulnerabilities.Vulnerability }
     * 
     */
    public Vulnerabilities.Vulnerability createVulnerabilitiesVulnerability() {
        return new Vulnerabilities.Vulnerability();
    }

    /**
     * Create an instance of {@link OriginalExternalEntity }
     * 
     */
    public OriginalExternalEntity createOriginalExternalEntity() {
        return new OriginalExternalEntity();
    }

    /**
     * Create an instance of {@link Assets.Asset }
     * 
     */
    public Assets.Asset createAssetsAsset() {
        return new Assets.Asset();
    }

    /**
     * Create an instance of {@link OriginalProcess }
     * 
     */
    public OriginalProcess createOriginalProcess() {
        return new OriginalProcess();
    }

    /**
     * Create an instance of {@link StringAndLink.Link }
     * 
     */
    public StringAndLink.Link createStringAndLinkLink() {
        return new StringAndLink.Link();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "appContainerBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesAppContainerBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesAppContainerBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "localDMZBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesLocalDMZBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesLocalDMZBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "internetBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesInternetBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesInternetBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "machineBoundary", scope = Diagram.Boundaries.class)
    public JAXBElement<Shape> createDiagramBoundariesMachineBoundary(Shape value) {
        return new JAXBElement<Shape>(_DiagramBoundariesMachineBoundary_QNAME, Shape.class, Diagram.Boundaries.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "fileSystem", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsFileSystem(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsFileSystem_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "html5LocalStorage", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsHtml5LocalStorage(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsHtml5LocalStorage_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "sqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsSqlDatabase(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsSqlDatabase_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "securityGateway", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSecurityGateway(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSecurityGateway_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "cache", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsCache(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsCache_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "webApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "webServer", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebServer(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebServer_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "thickClient", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsThickClient(Process value) {
        return new JAXBElement<Process>(_DiagramElementsThickClient_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "smartPhone", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsSmartPhone(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsSmartPhone_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "specialApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsSpecialApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsSpecialApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "externalWebApplication", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsExternalWebApplication(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsExternalWebApplication_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "cloudStorage", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsCloudStorage(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsCloudStorage_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "noSqlDatabase", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsNoSqlDatabase(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsNoSqlDatabase_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "webService", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsWebService(Process value) {
        return new JAXBElement<Process>(_DiagramElementsWebService_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "externalWebService", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsExternalWebService(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsExternalWebService_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "configurationFile", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsConfigurationFile(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsConfigurationFile_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStore }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "logFile", scope = Diagram.Elements.class)
    public JAXBElement<DataStore> createDiagramElementsLogFile(DataStore value) {
        return new JAXBElement<DataStore>(_DiagramElementsLogFile_QNAME, DataStore.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "browser", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsBrowser(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsBrowser_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "authorizedProvider", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsAuthorizedProvider(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsAuthorizedProvider_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Process }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "managedApplication", scope = Diagram.Elements.class)
    public JAXBElement<Process> createDiagramElementsManagedApplication(Process value) {
        return new JAXBElement<Process>(_DiagramElementsManagedApplication_QNAME, Process.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalEntity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "user", scope = Diagram.Elements.class)
    public JAXBElement<ExternalEntity> createDiagramElementsUser(ExternalEntity value) {
        return new JAXBElement<ExternalEntity>(_DiagramElementsUser_QNAME, ExternalEntity.class, Diagram.Elements.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringAndLink.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "link", scope = StringAndLink.class)
    public JAXBElement<StringAndLink.Link> createStringAndLinkLink(StringAndLink.Link value) {
        return new JAXBElement<StringAndLink.Link>(_StringAndLinkLink_QNAME, StringAndLink.Link.class, StringAndLink.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "ipSec", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsIpSec(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsIpSec_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "tcp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsTcp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsTcp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "udp", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsUdp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsUdp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "binary", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsBinary(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsBinary_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "namedPipe", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsNamedPipe(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsNamedPipe_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "http", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsHttp(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsHttp_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "smb", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSmb(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSmb_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "https", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsHttps(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsHttps_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "ssl", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSsl(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSsl_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "sql", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsSql(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsSql_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "rpcOrDcom", scope = Diagram.Flows.class)
    public JAXBElement<Flow> createDiagramFlowsRpcOrDcom(Flow value) {
        return new JAXBElement<Flow>(_DiagramFlowsRpcOrDcom_QNAME, Flow.class, Diagram.Flows.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "otherTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsOtherTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsOtherTrustSection_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "companyTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsCompanyTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsCompanyTrustSection_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "internetDmz", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsInternetDmz(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsInternetDmz_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "sandboxTrustSection", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsSandboxTrustSection(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsSandboxTrustSection_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "sharedNetwork", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsSharedNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsSharedNetwork_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockShape }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://www.tas.org/tas-schemas", name = "officeNetwork", scope = Diagram.Sections.class)
    public JAXBElement<BlockShape> createDiagramSectionsOfficeNetwork(BlockShape value) {
        return new JAXBElement<BlockShape>(_DiagramSectionsOfficeNetwork_QNAME, BlockShape.class, Diagram.Sections.class, value);
    }

}
