//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 09:10:53 AM CEST 
//


package com.tas.model.diagram;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for process complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="process">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.tas.org/tas-schemas}process">
 *       &lt;redefine>
 *         &lt;complexType name="process">
 *           &lt;complexContent>
 *             &lt;extension base="{https://www.tas.org/tas-schemas}blockElement">
 *               &lt;attribute name="sanitizeInput" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="sanitizeOutput" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="hasForgeryProtection" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="runLevel">
 *                 &lt;simpleType>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                     &lt;enumeration value="SANDBOX"/>
 *                     &lt;enumeration value="LOW_PRIVILEGE"/>
 *                     &lt;enumeration value="HIGH_PRIVILEGE"/>
 *                   &lt;/restriction>
 *                 &lt;/simpleType>
 *               &lt;/attribute>
 *               &lt;attribute name="sessionHasTimeouts" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="requiresAuthentication" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;attribute name="requiresAuthorization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *             &lt;/extension>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;attGroup ref="{https://www.tas.org/tas-schemas}additionalProcessProperties"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "process")
@XmlSeeAlso({
    com.tas.model.diagram.Diagram.Elements.WebApplication.class,
    com.tas.model.diagram.Diagram.Elements.WebService.class,
    com.tas.model.diagram.Diagram.Elements.WebServer.class
})
public class Process
    extends OriginalProcess
{


}
